# Relative to the rheo folder, if you specify a `oontent_dir`, 
# all of the `exclude` patterns become relative to this folder.
content_dir = "content"

# Default formats to compile (if not specified via CLI flags)
# Options: "pdf", "html", "epub"
# Default: ["pdf", "html"]
formats = ["html", "pdf"]

[epub.merge]
spine = ["severance-*.typ"]
title = "Severance Analysis"
